name: Update Notes

on:
  schedule:
    - cron: "0 9 * * *" # tous les jours à 9h UTC
  workflow_dispatch:

permissions:
  contents: write # ✅ donne le droit de push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install python-docx
      - name: Run update script
        run: python update.py
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update notes" || echo "Nothing to commit"
          git pull --rebase origin master
          git push origin masters

