name: Update Notes

permissions:
  contents: write   # autoriser le bot à push sur le dépôt

on:
  schedule:
    # Tous les jours à 9h du matin (UTC)
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx python-dateutil

      - name: Run update script
        run: python update.py

      - name: Commit changes
        run: |
          git config user.name "aldofwi"
          git config user.email "42814580+aldofwi@users.noreply.github.com"
          git add .
          git commit -m "Update notes" || echo "Nothing to commit"
          git fetch origin master
          git rebase origin/master || echo "No rebase needed"
          git push origin master --force